//
//  VideoViewModel.swift
//  Whistle
//
//  Created by 박상원 on 2023/08/23.
//

import AVFoundation
import Foundation

class VideoVM: ObservableObject {
  // FIXME: - 일단 임시로 제 서버 url로 테스트하는 코드입니다 - 유진
  var videos: [Video] = [
    .init(
      player: AVPlayer(url: URL(string: "http://35.72.228.224/adaStudy/test.mp4")!),
      user_name: "",
      profile_img: "",
      caption: "",
      video_url: "",
      music_singer: "",
      music_name: "",
      hashtags: "",
      content_whistle_count: 0,
      content_view_count: "",
      is_whistled: false,
      is_followed: false,
      is_bookmarked: false,
      is_hated: false),
    .init(
      player: AVPlayer(url: URL(string: "http://35.72.228.224/adaStudy/test2.mp4")!),
      user_name: "",
      profile_img: "",
      caption: "",
      video_url: "",
      music_singer: "",
      music_name: "",
      hashtags: "",
      content_whistle_count: 0,
      content_view_count: "",
      is_whistled: false,
      is_followed: false,
      is_bookmarked: false,
      is_hated: false),
    .init(
      player: AVPlayer(url: URL(string: "http://35.72.228.224/adaStudy/test.mp4")!),
      user_name: "",
      profile_img: "",
      caption: "",
      video_url: "",
      music_singer: "",
      music_name: "",
      hashtags: "",
      content_whistle_count: 0,
      content_view_count: "",
      is_whistled: false,
      is_followed: false,
      is_bookmarked: false,
      is_hated: false),
    .init(
      player: AVPlayer(url: URL(string: "http://35.72.228.224/adaStudy/test2.mp4")!),
      user_name: "",
      profile_img: "",
      caption: "",
      video_url: "",
      music_singer: "",
      music_name: "",
      hashtags: "",
      content_whistle_count: 0,
      content_view_count: "",
      is_whistled: false,
      is_followed: false,
      is_bookmarked: false,
      is_hated: false),
    .init(
      player: AVPlayer(url: URL(string: "http://35.72.228.224/adaStudy/test.mp4")!),
      user_name: "",
      profile_img: "",
      caption: "",
      video_url: "",
      music_singer: "",
      music_name: "",
      hashtags: "",
      content_whistle_count: 0,
      content_view_count: "",
      is_whistled: false,
      is_followed: false,
      is_bookmarked: false,
      is_hated: false),
    .init(
      player: AVPlayer(url: URL(string: "http://35.72.228.224/adaStudy/test2.mp4")!),
      user_name: "",
      profile_img: "",
      caption: "",
      video_url: "",
      music_singer: "",
      music_name: "",
      hashtags: "",
      content_whistle_count: 0,
      content_view_count: "",
      is_whistled: false,
      is_followed: false,
      is_bookmarked: false,
      is_hated: false),
    .init(
      player: AVPlayer(url: URL(string: "http://35.72.228.224/adaStudy/test.mp4")!),
      user_name: "",
      profile_img: "",
      caption: "",
      video_url: "",
      music_singer: "",
      music_name: "",
      hashtags: "",
      content_whistle_count: 0,
      content_view_count: "",
      is_whistled: false,
      is_followed: false,
      is_bookmarked: false,
      is_hated: false),
  ]
}
